[tool.black]
line-length = 120
target-version = ["py39"]

[tool.isort]
profile = "black"


[tool.pyright]
include = ["culturebot", "ext", "web"]
exclude = ["**/__init__.py", "tests/**", "ext/prettier/**"]

typeCheckingMode = "strict"
useLibraryCodeForTypes = true

reportImportCycles = false
reportMissingTypeStubs = false
reportIncompatibleMethodOverride = false
reportPrivateUsage = false
reportUnusedVariable = false

[tool.mypy]
ignore_missing_imports = true
install_types = true
non_interactive = true
