name: Run checks

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install nox
        run: |
          python -m pip install nox
      - name: lint
        run: |
          python -m nox -s lint

  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run prettier
        run: |
          npx prettier --check *.md
